### ISSUE TITLE
Zero impact of SRAM size on cycles

### ISSUE THREAD

**Issue by majid0jalili** [ARM-software/SCALE-Sim#12]
I swept the SRAM sizes from 256 to 8192, however I see exactly zero impact on statistics including  layer-based cycles. I was wondering why size of SRAM has zero impact on performance?

**Comment by AnandS09** [comment]
Hi @majid169 , what you observed is correct. The reason is that in SCALE-Sim we first determine the cycle counts assuming all the data is available in the SRAM, and then calculate the DRAM BW needed to keep the SRAM of the given size always fed. 
We chose this implementation since the design goal for the CNN accelerators is to keep the compute running at all times and thus determine the memory sizes such that it meets the system integration goals.
Let me know if that helps.
