### ISSUE TITLE
Bugs found in weight stationary

### ISSUE THREAD

**Issue by francisco-munoz** [ARM-software/SCALE-Sim#23]
Hi @AnandS09 @yuhao,

I think I have found a little, but significant bug in the code of weight stationary dataflow. It is just a line, but it affects to all the traces. 

Next, I explain the bug:

In the file _sram_traffic_ws.py_ in **line 72** is this line of code:

idx_start = v * dimension_cols

This means that when v folding exists, each loop jumps dimension_cols filters. However, as more than one filter can stay in the same column, the right code should be:

idx_start = v * dimension_cols * max_parallel_window

Otherwise you are fetching (max_parallel_window-1)*dimension_cols all over again and generating incorrectly all their traces. 

Thank you very much,
Francisco.

**Comment by pakiko24** [comment]
Hi again @AnandS09 @yuhao,

I've detected another tiny error in weight stationary dataflow. This does not modify the final result but do not let the user to change the parameter IfmapOffset.

If you do so, for example changing it from zero to 1000000, an error like this is produced:

![image](https://user-images.githubusercontent.com/22517459/53564712-e9126080-3b57-11e9-9692-ecf722f7ec2d.png)

fixing this issue is simple. It seems you forgot removing some lines while debugging. The ifmap offset is not added correctly to the traces. Just go to the file sram_traffic_ws.py and change slightly two functions:

Firstly, in function **gen_trace_ifmap_partial**  go to the line 387 and replace the line  "base_addr = 0" by "base_addr=ifmap_base".

Secondly, in function **gen_ifmap_trace**  (which is similar but without h_folding) do the same. Go to the line 284 and replace "base_addr = 0" by "base_addr=ifmap_base". The problem with this function is that ifmap_base is not in the argument list. Just add it in the function and in the line 151 where you call the function. 

With these changes the bug is fixed:

![image](https://user-images.githubusercontent.com/22517459/53565359-93d74e80-3b59-11e9-82f0-4f92dd1b70d2.png)

Best regards,
Francisco.
