### ISSUE TITLE
considering DRAM model 

### ISSUE THREAD

**Issue by KeeyoungSon** [ARM-software/SCALE-Sim#55]
Can SCALE-Sim consider the specific DRAM model??

if yes, how can we do that in given code?

Thank you.

**Comment by AnandS09** [comment]
Hi @KeeyoungSon ,

Thanks a lot for bringing this out. @HaFred is correct. SCALE-Sim generates the traces of requests to DRAM depending on the computation performed in the systolic array accelerator. It assumes stall free operation due to memory. 
I hope this helps. 

@whatmough : We can close this issue by labeling it as "question".
